####
# ATENTION:
# Replace all occurences of gcr with your project's name
####

# v2 syntax
version: "2"

# Named volumes
volumes:
  # MySQL Data
  gcr-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: gcr-mysql
    volumes:
      - gcr-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gcr
      - MYSQL_DATABASE=gcr
      - MYSQL_USER=gcr
      - MYSQL_PASSWORD=gcr

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: gcr-app
    volumes:
      - .:/var/www/app/public
    ports:
      - "80:8080"
    links:
      - mysql
